### PR TITLE
Include tracker dependency explicitly since Meteor 1.2 doesn't include it

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by kentonv** [comment]
thanks!

**Comment by ndarilek** [comment]
Cool, has this also been pushed to Atmosphere? Thanks.

**Comment by kentonv** [comment]
> Cool, has this also been pushed to Atmosphere? Thanks.

Done.

**Comment by ndarilek** [comment]
Excellent, thanks!

**Pull request merged**
