### PR TITLE
Add isInSandstorm variable on startup

### PR DESCRIPTION
**Pull request by simonv3**
Pretty straight forward, this is as suggested in #5. This would help a lot for apps with not-just-on-sandstorm functionality.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
So this is kinda like https://github.com/sandstorm-io/vagrant-spk/pull/77 for Meteor?

**Comment by simonv3** [comment]
@ocdtrekkie yeah, looks like it.

**Comment by simonv3** [comment]
Just realized this won't work because it doesn't really check an environment variable, it's just dependent on the package being included. That's no help! Just pushed an update that fixes that. 

If the user wants to run Meteor as if it's on Sandstorm they will have to set an env variable:

```export SANDSTORM=1```

Though maybe this could be put in https://github.com/jacksingleton/accounts-sandstorm-dev because that already makes that assumption?

**Comment by kentonv** [comment]
Hmm, not that currently it is dangerous to include the accounts-sandstorm package in a build of your app that isn't running on Sandstorm: users talking to your meteor app directly could spoof the Sandstorm headers to create bogus user accounts.

What we really want to do is *disable* accounts-sandstorm when not running on Sandstorm.

Arguably, also, when we *are* running on Sandstorm, accounts-sandstorm should enter "highlander mode" and disable all the *other* login mechanisms. This way, you can use the same package list between Sandstorm and non-Sandstorm, changing behavior entirely at runtime.

Note that this would be a backwards-incompatible change in that people who don't have `SANDSTORM=1` set (because they originally created their `sandstorm-pkgdef.capnp` before this was added by default) will find their code stops working until they go add it. I think that's OK -- we can alert (or even send pull requests to) all the Meteor app authors on the market.

@simonv3, would you be interested in working on this?

**Comment by simonv3** [comment]
@kentonv as a brute-force method - would it make sense to put all of the code inside of `check env variable` clauses?

I'd have to think about it - I've been pretty frustrated by the inability to define packages for specific environments in Meteor (test, etc) rather than all or nothing.

**Comment by kentonv** [comment]
@simonv3 Sorry, I'm not sure what you mean by "`check env variable` clauses". I'm thinking of wrapping everything in if blocks like `if (process.env.SANDSTORM) { ...code... }`.

**Comment by simonv3** [comment]
yeah that's exactly what I meant

**Comment by kentonv** [comment]
I decided to revert this PR for now because it implies that it is safe to include `accounts-sandstorm` in your app when not actually running on Sandstorm. This is actually not safe at all, since it would allow user spoofing.

I think we should re-introduce this setting in the future as part of a larger change in which `accounts-sandstorm` actually shuts itself off when not running under Sandstorm.

**Pull request merged**
