### PR TITLE
Use package for Meteor 1.5.1

### PR DESCRIPTION
**Pull request by dmitry-sher**
I've updated package for use with latest Meteor 1.5.1

The main changes are:
 - using of package.json in test meteor project
 - nailed version of server-ddp to 2.0.0
 - many packages in test project are updated

It gives some errors in console, but works. I was not digging deeply into the error cause, looks like some race condition.

### CODE REVIEW

**Comment by kentonv** [comment]
Thanks!

The addition of `.test-app/.DS_Store` looks like an accident. Could you rebase it out?

Why did `.test-app/.meteor/versions` go away? Is that intended?

**Comment by dmitry-sher** [comment]
i've rebased `.test-app/.DS_Store` following this manual: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

the `versions` file can be emptied -- it's regenerated by Meteor on project run.

**Comment by kentonv** [comment]
Hi dmitri,

Unfortunately it looks like you have have rewritten all of history, rather than just the commit that had the bad file, so now this isn't mergeable...

**Comment by kentonv** [comment]
I've now fixed this issue and pushed version 0.7.0.

**Pull request closed without merging**
