### PR TITLE
Decode special urlencoded characters in the name

### PR DESCRIPTION
**Pull request by mquandalle**

### CODE REVIEW

**Comment by kentonv** [comment]
Thanks! We recently started url-encoding this and hadn't updated the Meteor package yet. (@dwrensha)

Hmm, I think you really want to do the decoding on line 41, though, or at least make sure `credentials.name` ends up holding the decoded version, since that's what we return to the client.

**Comment by mquandalle** [comment]
Hum, I misunderstood this code. But it was just a github patch to raise this issue, hope you can update the published package soon :-)

(Not related, but is there any way currently for the sandboxed meteor application to get the instance name?)

**Comment by mquandalle** [comment]
I modified the PR.

**Comment by kentonv** [comment]
Thanks!

> Not related, but is there any way currently for the sandboxed meteor application to get the instance name?

The title? No, not currently. We should probably add that to the API...

**Pull request merged**
